swagger: "2.0"
info:
  description: "This is the simple registration backend."
  version: "0.1.0"
  title: "Volunteer Registration Form API"
  contact:
    email: "pavel.suchmann@gmail.com"
basePath: "/volunteer-registration"
schemes:
- "https"
- "http"
paths:
  /skills:
    get:
      summary: "Get the Skills hierarchy"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Retrieve the hierarchy of C.D skills"
          schema:
            $ref: "#/definitions/SkillHierarchy"
  /volutneers:
    post:
      summary: "Create the new volunteer record"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Volunteer information to store"
        required: true
        schema:
          $ref: "#/definitions/NewVolunteer"
      responses:
        "200":
          description: "New Volunteer Record Created"
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: "Error occured"
          schema:
            $ref: "#/definitions/ApiResponse"
definitions:
  SkillHierarchy:
    type: "object"
    required:
    - "skills"
    properties:
      skills:
        type: "array"
        minimum: 0
        items:
          type: "object"
          required:
          - "skill"
          - "details"
          properties:
            skill:
              type: "string"
              example: "Design"
            details:
              type: "array"
              minimum: 1
              items:
                type: "object"
                required:
                - "text"
                - "id"
                properties:
                  text:
                    type: "string"
                  id:
                    type: "string"
              example:
                - id: "recu71mPBhoYZWTtq"
                  text: "Mobilní"
                - id: "recwSqRn0BRKxN7IF"
                  text: "Web"
            mentor_id:
              type: "string"
              description: "Ask about mentorship if this optional property is present"
              example: "recFgcjWmfXN42HyM"
            senior_id:
              type: "string"
              description: "Ask about seniorship if this optional property is present"
              example: "recwSqRn0BRKxN7IF"
  NewVolunteer:
    type: "object"
    required:
    - "name"
    - "email"
    - "options_selected"
    properties:
      name:
        type: "string"
        example: "Dobromil Volný"
      email:
        type: "string"
        format: "email"
        example: "dvolny@example.com"
      options_selected:
        type: "array"
        minimum: 0
        items:
          type: "string"
          example:
          - "recwSqRn0BRKxN7IF"
          - "recu71mPBhoYZWTtq"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
        example: 400042
        description: "Internal error code."
      message:
        type: "string"
        example: "This is the example error message."
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"